---
title: "S3_to_Spark"
output: html_document
---

```{r}
#Initialize Spark Session----
if (exists("sc")) {
  spark_disconnect(sc)
}

conf <- spark_config()
conf$spark.app.name <- "NYC Taxi"
conf$spark.hadoop.fs.s3a.endpoint <- "s3.amazonaws.com"
conf$spark.hadoop.fs.s3a.impl <- "org.apache.hadoop.fs.s3a.S3AFileSystem"
conf$spark.hadoop.fs.s3a.aws.credentials.provider <- "org.apache.hadoop.fs.s3a.AnonymousAWSCredentialsProvider"
conf$spark.sql.parquet.enableVectorizedReader <- "false"

sc <- spark_connect(master = "local", version = "3.5.0", config = conf)

yellow_read_schema <- list(
  #Original Columns
  #(forced to double when applicable)
  VendorID              = "double",
  tpep_pickup_datetime  = "timestamp",
  tpep_dropoff_datetime = "timestamp",
  passenger_count       = "double",
  trip_distance         = "double",
  PULocationID          = "double",
  DOLocationID          = "double",
  payment_type          = "double",
  fare_amount           = "double",
  tip_amount            = "double",
  total_amount          = "double",
  
  # Engineered Columns
  #(created in loop)
  year                  = "double",
  month                 = "double",
  total_fees            = "double"
)
```



```{r}
#main directory (all files)
#s3_file_directory <- "s3a://cs4265-nyc-taxi-project/data/yellow_split/"

#directory for much smaller set of test files (proof of concept)
s3_file_directory <- "s3a://cs4265-nyc-taxi-project/data/yellow_test/" 

yellow_s3_data <- spark_read_parquet(
  sc = sc,
  name = "yellow_s3_data",
  path = s3_file_directory,
  columns = yellow_read_schema,
  options = list(mergeSchema = "false"),
  memory = FALSE
)

#yellow_normalized <- yellow_s3_data |>
#  mutate(
#    # Ensure IDs are doubles (helpful for joins later)
#    VendorID     = as.double(VendorID),
#    PULocationID = as.double(PULocationID),
#    DOLocationID = as.double(DOLocationID)
#  )

print(yellow_s3_data)
```

```{r}
revenue_over_time <- yellow_s3_data |>
  group_by(year) |>
  summarize(
    total_rev = sum(total_amount),
    mean_rev = mean(total_amount),
    n = n()
  ) |>
  sdf_register("revenue_over_time")

tbl_cache(sc, "revenue_over_time")

revenue_over_time <- revenue_over_time |> collect()

```


```{r}
library(ggplot2)
library(scales)

rev_plot <- ggplot(revenue_over_time, aes(x = year, y = total_rev)) +
  geom_bar(stat = "identity", fill = "gold") +
  labs(
    x = "Year",
    y = "Total Revenue (USD)",
    title = "Total Revenue of NYC Yellow Taxis by Year"
  ) +
  scale_y_continuous(labels = label_dollar()) +
  theme_minimal() +
  theme(
    plot.background = element_rect(fill = "black"),
    text = element_text(color = "white"),
    axis.text.x = element_text(color = "white"),
    axis.text.y = element_text(color = "white"),
    panel.grid = element_line(color = "gray15")
  )
  
print(rev_plot)
```

