---
title: "Data Pipeline Validation Report"
date: "`r Sys.Date()`"
output: 
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
# include=FALSE prevents this setup code/warnings from showing in the final report
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = getwd())

#Initialize Spark Session----
if (exists("sc")) {
  spark_disconnect(sc)
}


# 1. Connect to Spark
if (exists("sc")) {
  spark_disconnect(sc)
}

conf <- spark_config()
conf$spark.app.name <- "NYC Taxi"
conf$spark.hadoop.fs.s3a.endpoint <- "s3.amazonaws.com"
conf$spark.hadoop.fs.s3a.impl <- "org.apache.hadoop.fs.s3a.S3AFileSystem"
conf$spark.hadoop.fs.s3a.aws.credentials.provider <- "org.apache.hadoop.fs.s3a.AnonymousAWSCredentialsProvider"
conf$spark.sql.parquet.enableVectorizedReader <- "false"

sc <- spark_connect(master = "local", version = "3.5.0", config = conf)

```

```{r data pull, include=FALSE}

yellow_read_schema <- list(
  #Original Columns
  #(forced to double when applicable)
  VendorID              = "double",
  tpep_pickup_datetime  = "timestamp",
  tpep_dropoff_datetime = "timestamp",
  passenger_count       = "double",
  trip_distance         = "double",
  PULocationID          = "double",
  DOLocationID          = "double",
  payment_type          = "double",
  fare_amount           = "double",
  tip_amount            = "double",
  total_amount          = "double",
  
  # Engineered Columns
  #(created in loop)
  year                  = "double",
  month                 = "double",
  total_fees            = "double"
)


s3_file_directory <- "s3a://cs4265-nyc-taxi-project/data/yellow_data/" 

yellow_s3_data <- spark_read_parquet(
  sc = sc,
  name = "yellow_s3_data",
  path = s3_file_directory,
  columns = yellow_read_schema,
  options = list(mergeSchema = "false"),
  memory = FALSE
)
```


```{r data quality, echo=FALSE}
#Assessment of general data quality
data_quality <- yellow_s3_data |>
  summarize(
    total_records = n(),
    missing_distance = sum(as.integer(is.na(trip_distance))),
    missing_pickup = sum(as.integer(is.na(tpep_pickup_datetime))),
    missing_dropoff = sum(as.integer(is.na(tpep_dropoff_datetime))),
    
   incorrect_sum_fees = sum(as.integer(total_amount != fare_amount + tip_amount + total_fees))
  ) |>
  collect()

knitr::kable(data_quality)
```

```{r logical validation, echo=FALSE}
# Logical validation metrics
validation_metrics <- yellow_s3_data |>
  summarize(
    total_trips = n(),
    valid_distance = sum(as.integer(trip_distance > 0)),
    valid_fare = sum(as.integer(total_amount > 0))
  ) |>
  mutate(
    pct_valid_distance = (valid_distance / total_trips) * 100,
    pct_valid_fare = (valid_fare / total_trips) * 100
  ) |>
  collect()

knitr::kable(validation_metrics)
```

```{r edge cases, echo=FALSE}
#Edge case documentation
extreme_fares <- yellow_s3_data |>
  arrange(desc(total_amount)) |>
  select(tpep_pickup_datetime, trip_distance, fare_amount, total_amount) |>
  head(5) |>
  collect()

knitr::kable(extreme_fares)
```

```{r runtime-testing, echo=FALSE}
library(tictoc)
# Start timer
tic("Yearly Revenue Aggregation")

# Run the heavy Spark aggregation
perf_test <- yellow_s3_data |>
  group_by(year) |>
  summarize(total_rev = sum(total_amount, na.rm = TRUE)) |>
  collect()

# Save the timing result to a variable[cite: 1]
timer_log <- toc(quiet = TRUE) 
print(timer_log$callback_msg)
```


